### ISSUE TITLE
Traceback error while writing micropython on the board

### ISSUE THREAD

**Issue by fabse-hack** [BPI-STEAM/BPI-Leaf-S3-Doc#1]
command:
python -m esptool --chip esp32s3 --port COM11 --baud 921600 write_flash 0x0 BPI-Leaf-S3_MicroPython_v1.19.1.bin

error:
Writing at 0x000126a9... (3 %)Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

**Comment by fabse-hack** [comment]
success flashed with ubuntu
